"""Production-source boundary: extension eligibility + exclusion reasons."""

from analysis_wrapper.callgraph import sources


def test_ext_of_recognizes_families_and_declaration():
    assert sources.ext_of("a.ts") == ".ts"
    assert sources.ext_of("a.mjs") == ".mjs"
    assert sources.ext_of("service.go") == ".go"
    assert sources.ext_of("types.d.ts") == ".d.ts"
    assert sources.ext_of("styles.css") == ""
    assert sources.ext_of("README") == ""


def test_production_paths_are_not_excluded():
    assert sources.path_exclusion_reason("src/service/user.ts") == ""
    assert sources.path_exclusion_reason("internal/handlers/auth.go") == ""


def test_exclusion_reasons_by_directory_and_name():
    assert sources.path_exclusion_reason("src/__tests__/x.ts") == "test"
    assert sources.path_exclusion_reason("src/user.test.ts") == "test"
    assert sources.path_exclusion_reason("pkg/user_test.go") == "test"
    assert sources.path_exclusion_reason("src/mocks/api.ts") == "mock"
    assert sources.path_exclusion_reason("pkg/user_mock.go") == "mock"
    assert sources.path_exclusion_reason("src/fixtures/data.ts") == "fixture-or-example"
    assert sources.path_exclusion_reason("examples/demo.ts") == "fixture-or-example"
    assert sources.path_exclusion_reason("api/user.pb.go") == "generated"
    assert sources.path_exclusion_reason("api/user.gen.go") == "generated"
    assert sources.path_exclusion_reason("vendor/x/y.go") == "vendored"
    assert sources.path_exclusion_reason("dist/bundle.js") == "build-output"
    assert sources.path_exclusion_reason("db/migrations/001.ts") == "migration-or-seed"
    assert sources.path_exclusion_reason("types.d.ts") == "declaration"


def test_config_files_are_excluded():
    assert sources.path_exclusion_reason("vite.config.ts") == "config"
    assert sources.path_exclusion_reason("jest.config.js") == "config"
    assert sources.path_exclusion_reason(".eslintrc.js") == "config"
    assert sources.path_exclusion_reason("gulpfile.js") == "config"


def test_tier2_dirs_disclosed():
    reason = sources.path_exclusion_reason("gen/api.ts", tier2_dirs=frozenset({"gen"}))
    assert reason == "tier2-excluded"


def test_walk_splits_production_and_excluded(tmp_path):
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "user.ts").write_text("export const a = 1;\n")
    (tmp_path / "src" / "user.test.ts").write_text("test('x', () => {});\n")
    (tmp_path / "src" / "mocks").mkdir()
    (tmp_path / "src" / "mocks" / "api.ts").write_text("export const m = 1;\n")
    (tmp_path / "vite.config.ts").write_text("export default {};\n")
    (tmp_path / "node_modules").mkdir()
    (tmp_path / "node_modules" / "dep.js").write_text("module.exports = 1;\n")

    prod, cand, excl = sources.walk(tmp_path, exts=sources.JS_EXTS)
    names = {p.name for p in prod}
    assert names == {"user.ts"}
    assert cand == {".ts": 1}
    assert excl.get("test") == 1
    assert excl.get("mock") == 1
    assert excl.get("config") == 1
    # node_modules is pruned entirely — never descended, never counted.
    assert "vendored" not in excl


def test_walk_detects_generated_go_marker(tmp_path):
    (tmp_path / "a.go").write_text("// Code generated by protoc. DO NOT EDIT.\npackage a\n")
    (tmp_path / "b.go").write_text("package b\nfunc F() {}\n")
    prod, cand, excl = sources.walk(tmp_path, exts=sources.GO_EXTS)
    assert {p.name for p in prod} == {"b.go"}
    assert excl.get("generated") == 1
