"""57B-11 S4: Tier-2 exclusions are derived per repo, evidence-backed."""

from doctor_wrapper.discovery.generated import derive


def _write(path, content=""):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def test_swagger_bundle_dir_excluded(tmp_path):
    _write(tmp_path / "docs" / "docs.go", "package docs")
    _write(tmp_path / "docs" / "swagger.json", "{}")
    report = derive(tmp_path)
    assert report.exclusions == ["docs"]
    assert "swagger" in report.evidence[0]


def test_docs_with_real_prose_not_excluded(tmp_path):
    _write(tmp_path / "docs" / "architecture.md", "# Design\n")
    assert derive(tmp_path).exclusions == []


def test_static_public_excluded_but_source_public_kept(tmp_path):
    _write(tmp_path / "public" / "logo.svg", "<svg/>")
    _write(tmp_path / "public" / "lib.min.js", "x")
    assert derive(tmp_path).exclusions == ["public"]

    _write(tmp_path / "public" / "app.js", "real();")
    assert derive(tmp_path).exclusions == []


def test_migrations_excluded_only_with_migration_shaped_files(tmp_path):
    for i in range(4):
        _write(tmp_path / "migrations" / f"2024010{i}-add-table.js", "up();")
    report = derive(tmp_path)
    assert report.exclusions == ["migrations"]
    assert "migration" in report.evidence[0]


def test_migrations_dir_with_ordinary_code_kept(tmp_path):
    _write(tmp_path / "migrations" / "runner.js", "run();")
    _write(tmp_path / "migrations" / "helpers.js", "help();")
    assert derive(tmp_path).exclusions == []


def test_generated_marker_directory_excluded(tmp_path):
    for i in range(3):
        _write(tmp_path / "gen" / f"api_{i}.go",
               "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage gen")
    report = derive(tmp_path)
    assert report.exclusions == ["gen"]
    assert "generated-code markers" in report.evidence[0]


def test_handwritten_directory_never_excluded(tmp_path):
    _write(tmp_path / "services" / "user.go", "package services")
    _write(tmp_path / "services" / "auth.go", "package services")
    assert derive(tmp_path).exclusions == []


def test_nothing_is_generic_empty_repo_empty_report(tmp_path):
    report = derive(tmp_path)
    assert report.exclusions == [] and report.evidence == []
